const data = [{
    "id": 1,
    "name": "gpenddreth0",
    "password": "RkVdO1ABTPz",
    "email": "rhappel0@google.pl"
  }, {
    "id": 2,
    "name": "cculvey1",
    "password": "ZAoxECB",
    "email": "igwyllt1@youku.com"
  }, {
    "id": 3,
    "name": "ilafflina2",
    "password": "6L8VWq88X",
    "email": "hbarnewall2@domainmarket.com"
  }, {
    "id": 4,
    "name": "dklyner3",
    "password": "UqyEIr2JvQv",
    "email": "qgiovanazzi3@dagondesign.com"
  }, {
    "id": 5,
    "name": "kstrathe4",
    "password": "BEEYBrx",
    "email": "ithackwray4@hibu.com"
  }, {
    "id": 6,
    "name": "gwilne5",
    "password": "BChhmkYGpDUF",
    "email": "lbonwick5@gnu.org"
  }, {
    "id": 7,
    "name": "nlynnett6",
    "password": "nQe0luSibK7",
    "email": "wvasyutochkin6@sun.com"
  }, {
    "id": 8,
    "name": "mcrotch7",
    "password": "2BSzq4GRF",
    "email": "mprettyjohn7@nationalgeographic.com"
  }, {
    "id": 9,
    "name": "jbrower8",
    "password": "Nus7yu7RdZay",
    "email": "bhaycox8@wikispaces.com"
  }, {
    "id": 10,
    "name": "twaitland9",
    "password": "5HbjYK8jegqP",
    "email": "nervin9@163.com"
  }]
  
export default data 